###Peliculas
GET http://localhost:8080/analytics/movie
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlZGR5QG5vcmVwbHkuY29tIiwiZXhwIjoxNjU0MDk3ODY3LCJpYXQiOjE2NTQwODc4Njd9.i6tmWfrwbGXUY7URVyHyYPauCtbgT1nAjTYJj6kxgLNW1t-TzqotaUH31BDfajzLuM2PA67rqeqjp7PzU3fggg

###Pelicula en especifico
GET http://localhost:8080/analytics/movie/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlZGR5QG5vcmVwbHkuY29tIiwiZXhwIjoxNjU0MDk3ODY3LCJpYXQiOjE2NTQwODc4Njd9.i6tmWfrwbGXUY7URVyHyYPauCtbgT1nAjTYJj6kxgLNW1t-TzqotaUH31BDfajzLuM2PA67rqeqjp7PzU3fggg

###Generos
GET http://localhost:8080/analytics/genre
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2YWxlQG5vcmVwbHkuY29tIiwiZXhwIjoxNjU0MTAwMDUyLCJpYXQiOjE2NTQwOTAwNTJ9.0o5IcVmmlfuMCiLvzW6J16lDH6-lXcnC0AQsHGpspjv70wCw7Z3M4rBhnD1kasvpl4bPmM8UUZeUXo4I2AgTLA

###Generos
GET http://localhost:8080/analytics/genre/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2YWxlQG5vcmVwbHkuY29tIiwiZXhwIjoxNjU0MTAwMDUyLCJpYXQiOjE2NTQwOTAwNTJ9.0o5IcVmmlfuMCiLvzW6J16lDH6-lXcnC0AQsHGpspjv70wCw7Z3M4rBhnD1kasvpl4bPmM8UUZeUXo4I2AgTLA


###Usuarios
GET http://localhost:8080/analytics/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlZGR5QG5vcmVwbHkuY29tIiwiZXhwIjoxNjU0MDk3ODY3LCJpYXQiOjE2NTQwODc4Njd9.i6tmWfrwbGXUY7URVyHyYPauCtbgT1nAjTYJj6kxgLNW1t-TzqotaUH31BDfajzLuM2PA67rqeqjp7PzU3fggg
