###
GET http://localhost:8080/cart
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhbGV4QG5vcmVwbHkuY29tIiwiZXhwIjoxNjQ5NjUwNDMyLCJpYXQiOjE2NDk2NDA0MzJ9.fsltdxUEJTNNTHhqTUglHTuSZNvmk__37QAQeBr1ZoV19i3e8yIIM5XLwN5lLLxkMeAgZHsBz33UG8GEwU2irw
###
POST http://localhost:8080/cart
Content-Type: application/json

{    
    "movieid": 1,
    "title": "Harry Potter y la Orden del Fenix",
    "description": null,
    "releaseyear": 0,
    "cost": 15.5,
    "rating": "PG-13",
    "genre": "fantasia",
    "imagelink": "https://raw.githubusercontent.com/alexander-sosa/films-and-chill/main/images/harrypotter.jpg",
    "tuplestatus": true,
    "lastupdate": "2022-03-31T02:58:38.000+00:00"
}

###
DELETE http://localhost:8080/cart/1

###
DELETE http://localhost:8080/cart