###
POST http://localhost:8080/movie/new
Content-Type: application/json

{    
    "title": "Rogue One: Una Historia de Star Wars",
    "description": "La batalla de la rebelión por conseguir los planos de la Estrella de la Muerte",
    "release_year": 2016,
    "cost": 16.9,
    "stock": 10,
    "rating_id": 2,
    "genre_id": 1,
    "image_link": "https://raw.githubusercontent.com/alexander-sosa/films-and-chill/main/images/harrypotter.jpg"
}