###
POST http://localhost:8080/movie
Content-Type: application/json

{    
    "title": "Rogue One: Una Historia de Star Wars",
    "description": "La batalla de la rebelión por conseguir los planos de la Estrella de la Muerte",
    "releaseyear": 2016,
    "cost": 16.9,
    "stock": 10,
    "ratingid": 2,
    "genreid": 1,
    "imagelink": "https://raw.githubusercontent.com/alexander-sosa/films-and-chill/main/images/harrypotter.jpg"
}

###
PUT http://localhost:8080/movie/6
Content-Type: application/json

{
    "title": "Rogue One",
    "description": "Una nueva descripcion",
    "releaseyear": 2016,
    "cost": 12.2,
    "ratingid": 2,
    "genreid": 1,
    "imagelink": "https://raw.githubusercontent.com/alexander-sosa/films-and-chill/main/images/harrypotter.jpg",
    "stock": 8
  }

###
DELETE http://localhost:8080/movie/1