### Getting purchase list...
GET http://localhost:8080/purchase
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ2YWxlQG5vcmVwbHkuY29tIiwiZXhwIjoxNjUzMjg1Njc2LCJpYXQiOjE2NTMyNzU2NzZ9.-Lv9DBeav9R8cocJxjTxh5oVRtymcXelyi5dTLYfxhYp--y9SZaLX8r3jWEC5r7JAcWLwInLNmC3cyq5e_FJUA
Accept: application/json