###
POST http://localhost:8080/purchase
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0dXNlckBnbWFpbC5jb20iLCJleHAiOjE2NTMzMjcxODYsImlhdCI6MTY1MzMxNzE4Nn0.6VRZpBSpG5HCxDbO1wSGxUvvNYZIWFH_s8I2nxx7gp80aEAnPTts7rTo0f9x-bQz9xSrxhxXdpLwX2iHQJPZzQ
Content-Type: application/json

{    
    "purchase": {
        "userid" : 2,
        "totalcost": 16.5,
        "address": "Direccion de prueba"
    },
    "moviepurchases": [
        {
            "movieid": 1,
            "quantity": 2
        },
        {
            "movieid": 2,
            "quantity": 2
        }
    ]
}