### Getting purchase list...
GET http://localhost:8080/purchase
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlZGR5QG5vcmVwbHkuY29tIiwiZXhwIjoxNjUzNzAyNDA5LCJpYXQiOjE2NTM2OTI0MDl9.akqsX83jJK9fmeKRokgC1KSIEVkxN4n0U3V4AgePJxgG_8AhnNCK0mlztH3V_N8cbqdtXcFiVwMQe0R9GLWz0w
Accept: application/json