###
PUT http://localhost:8080/user/permission
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0dXNlckBnbWFpbC5jb20iLCJleHAiOjE2NDk5MDYzNzksImlhdCI6MTY0OTg5NjM3OX0.8Yrbcj--eZ1W_GzTOUbnpbgTSwBHK58rNhRlKxWcWxLM_saimqwxFLrl93uJzdO8kUlVnuOXOBBMf-mC36uYag
Content-Type: application/json

{
    "user_editor_id": 1,
    "user_editee_id": 1,
    "permission_id": 2
}

###
PUT http://localhost:8080/user/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlZGR5M0Bub3JlcGx5LmNvbSIsImV4cCI6MTY1MDQ3NjQwNSwiaWF0IjoxNjUwNDY2NDA1fQ.ewDso9nh0kWc4CDR5pUOtzB23s1yv03vqoc5OFBOX1VesiHAe0yW-b5ct2xNpsoCBY8j0j5M156Op0fv6SRuiQ
Content-Type: application/json

  {
    "name": "Edgar Fabian",
    "lastname": "Carrasco",
    "permission_id": 1,
    "username": "eddy3@noreply.com",
    "pass": "12345678",
    "tuple_status": true
  }