###
PUT http://localhost:8080/user/permission
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJlZGR5QG5vcmVwbHkuY29tIiwiZXhwIjoxNjQ5ODk0NTA4LCJpYXQiOjE2NDk4ODQ1MDh9.690TdaQJVVx4MOKt7i_b8zbublCf38sWds8VyuC_zPfljS9yV-NDx8DIuJcYA3FSiz3d3x83JyLLpUka5J77JQ
Content-Type: application/json

{
    "user_id": 1,
    "permission_id": 2
}