###
PUT http://localhost:8080/user/permission
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0dXNlckBnbWFpbC5jb20iLCJleHAiOjE2NDk5MDE2NDAsImlhdCI6MTY0OTg5MTY0MH0.c84827awe-bFYzJjwjQ2UR9U2laKTncUotCPX_NfhOQP1h5GWoWCq1gG9H1P9p9ELu7Yxx6Jnj6pLA7K-gf0hw
Content-Type: application/json

{
    "user_id": 1,
    "permission_id": 1
}