###Guardar nuevo usuario
POST http://localhost:8080/user
Content-Type: application/json

{
    "name": "Edgar",
    "lastname": "Carrasco",
    "permission_id": 1,
    "username": "eddy10@noreply.com",
    "pass": "12345678"
}